### ISSUE TITLE
Add content for UKE hamburg workshop

### ISSUE THREAD

**Issue by jsheunis** [datalad/tutorials#3]
Videos: https://www.youtube.com/playlist?list=PLEQHbPfpVqU5RSPiyFuPdDlSUEd-XoPV-

**Comment by adswa** [comment]
I just found this repo again, and then found these issues! How can I help? Do you intend to turn it into notebooks, or add links to a resource list?

**Comment by jsheunis** [comment]
The idea is to keep track of all our educational content, whether it's notebooks or talks or other material. So in this specific case I think it's fine to just add the list of videos and titles to the readme, probably in the "In-depth" section. I meant to do this shortly after creating the issue ... 🙃 

And now that you've commented here, I also see that my most recent commit screwed up the table rendering!

If you have time to add the UKE videos to the table, please feel free to do so. But I'll get to it eventually if you can't find the time 👍

**Comment by jsheunis** [comment]
I just fixed the table rendering

**Comment by adswa** [comment]
done in #16

**Comment by jsheunis** [comment]
awesome, thanks!
